name = "ff14markethelper"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"

[env.production]
name = "ff14markethelper"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"